server:
  port: 9017

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:authority;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS newways

  jpa:
    hibernate:
      ddl-auto: create-drop