server:
  port: 9017
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pilot
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true